spring.application.name=atlasmentor

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/atlas_mentor_dev
spring.datasource.url=jdbc:postgresql://localhost:5432/atlas_mentor
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=akshaya
spring.datasource.password=Shaya@1234

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=athreya2420@gmail.com
spring.mail.password=xvez evbp ygci kqjj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400

# Application Configuration
app.frontend.url=http://localhost:4200

# Logging Configuration
logging.level.com.lab.atlasmentor.config.JwtAuthenticationFilter=DEBUG
logging.level.com.lab.atlasmentor.service.JwtService=DEBUG
