-- Weekly Accountability Templates: role- AND cycle-month-scoped templates, each broken into
-- 4 independently-configured weeks (own due weekday, own question set). Both
-- weekly_accountability_questions and weekly_accountability_responses were dead scaffolding
-- before this migration (Hibernate ddl-auto=update had materialized them from entities never
-- wired to any service/controller, both empty - verified before writing this migration), so
-- this is a single from-scratch definition rather than an incremental ALTER chain.

-- 1. weekly_accountability_templates - same publish lifecycle (DRAFT/ACTIVE) as task_bundles,
--    now scoped per (role, cycle_month) instead of per role alone: a role can have a
--    different ACTIVE template for August 2026 vs. September 2026.
CREATE TABLE weekly_accountability_templates (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(200) NOT NULL,
    target_role_id    BIGINT NOT NULL REFERENCES roles(id),
    cycle_month       DATE NOT NULL,
    -- DRAFT is left only via publish and never re-entered; ACTIVE/INACTIVE toggle back and
    -- forth via the activate/deactivate endpoint (PATCH .../{id}/status).
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
                          CONSTRAINT chk_weekly_acct_templates_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
    -- Always the 1st of the month - enforced here rather than trusted to application code,
    -- since the (role, cycle_month) uniqueness below depends on it being a stable key.
    CONSTRAINT chk_weekly_acct_templates_cycle_month_first_of_month CHECK (EXTRACT(DAY FROM cycle_month) = 1),
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    created_by        BIGINT,
    updated_by        BIGINT
);

CREATE INDEX idx_weekly_acct_templates_role ON weekly_accountability_templates(target_role_id);
CREATE INDEX idx_weekly_acct_templates_role_month ON weekly_accountability_templates(target_role_id, cycle_month);

-- Enforces "one ACTIVE template per role + cycle month" only at the point it matters
-- (ACTIVE) - multiple DRAFT templates for the same role/month are still allowed while one
-- is being drafted/edited.
CREATE UNIQUE INDEX uk_weekly_acct_templates_active_role_month
    ON weekly_accountability_templates(target_role_id, cycle_month)
    WHERE status = 'ACTIVE';

-- 2. weekly_accountability_weeks (new) - the 4 fixed week slots of a template. All 4 rows
--    always exist once a template is created (even with zero questions - "Not scheduled" is
--    a real, persisted state, not an absent row). day_range covers every calendar day of the
--    month: weeks 1-3 are fixed 7-day blocks, week 4 runs from day 22 through the actual
--    last day of cycle_month (28-31 depending on the month) - computed once at template
--    creation time since cycle_month is already known, so no month-length special-casing is
--    needed anywhere else that reads day_range_end.
CREATE TABLE weekly_accountability_weeks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id       BIGINT NOT NULL REFERENCES weekly_accountability_templates(id) ON DELETE CASCADE,
    week_number       SMALLINT NOT NULL CONSTRAINT chk_weekly_acct_weeks_week_number CHECK (week_number BETWEEN 1 AND 4),
    day_range_start   SMALLINT NOT NULL,
    day_range_end     SMALLINT NOT NULL,
    -- Nullable: an unscheduled ("Not scheduled") week may have no due weekday set yet.
    -- Display/reminder text only - not an enforced submission deadline (see
    -- WeeklyAccountabilityResponseService javadoc).
    due_weekday       VARCHAR(10) CONSTRAINT chk_weekly_acct_weeks_due_weekday
                          CHECK (due_weekday IS NULL OR due_weekday IN
                              ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    created_by        BIGINT,
    updated_by        BIGINT,
    CONSTRAINT uk_weekly_acct_weeks_template_week_number UNIQUE (template_id, week_number)
);

CREATE INDEX idx_weekly_acct_weeks_template ON weekly_accountability_weeks(template_id);

-- 3. weekly_accountability_questions - now hangs off a week, not the template directly.
DROP TABLE IF EXISTS weekly_accountability_responses;
DROP TABLE IF EXISTS weekly_accountability_questions;

CREATE TABLE weekly_accountability_questions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id       BIGINT NOT NULL REFERENCES weekly_accountability_weeks(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    created_by    BIGINT,
    updated_by    BIGINT
);

CREATE INDEX idx_weekly_acct_questions_week ON weekly_accountability_questions(week_id);

-- 4. weekly_accountability_responses - adds an explicit week_id FK (more explicit than
--    re-deriving the owning week from checkpoint_date on every read, and avoids re-running
--    the day-range lookup for historical rows whose template may since have changed).
CREATE TABLE weekly_accountability_responses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_user_id  BIGINT NOT NULL REFERENCES users(id),
    week_id           BIGINT NOT NULL REFERENCES weekly_accountability_weeks(id) ON DELETE CASCADE,
    question_id       BIGINT NOT NULL REFERENCES weekly_accountability_questions(id) ON DELETE CASCADE,
    checkpoint_date   DATE NOT NULL,
    answer_text       TEXT,
    answered_at       TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    created_by        BIGINT,
    updated_by        BIGINT,
    CONSTRAINT uk_weekly_acct_responses_employee_question_date
        UNIQUE (employee_user_id, question_id, checkpoint_date)
);

CREATE INDEX idx_weekly_acct_responses_employee ON weekly_accountability_responses(employee_user_id);
CREATE INDEX idx_weekly_acct_responses_week ON weekly_accountability_responses(week_id);
CREATE INDEX idx_weekly_acct_responses_question ON weekly_accountability_responses(question_id);
CREATE INDEX idx_weekly_acct_responses_checkpoint_date ON weekly_accountability_responses(checkpoint_date);
