-- Weekly Accountability Assignments: the persisted output of the Saturday-only assignment
-- cron (WeeklyAccountabilityAssignmentSchedulerService). Exactly one row per template,
-- holding "which of the 4 weeks is currently assigned" - written only by that cron (primary
-- Saturday trigger, startup catch-up, or periodic safety-net, same three-trigger shape as the
-- nightly task-instantiation cron), never recomputed live from today's date against a week's
-- day_range on a read path. GET /my-template and submit both simply read whatever this table
-- says is current; day_range_start/end on weekly_accountability_weeks remain for display/
-- record-keeping only.
--
-- One row per template (not per employee): every employee under a template's role shares the
-- same currently-assigned week, so there is nothing to fan out per employee here - that mirrors
-- how the read path already resolves "current week" per role, not per individual.
--
-- DROP + CREATE, not a bare CREATE: same reason V19 does this for weekly_accountability_
-- questions/responses - Hibernate's ddl-auto=update can (and, on this table, already did in
-- dev via a devtools restart) materialize a table from the entity mapping before this
-- migration ever runs. That auto-generated version is missing the CHECK constraints,
-- named unique constraint, and ON DELETE CASCADE below, so it isn't safe to just leave in
-- place - this is cron-repopulatable "current state," not historical data, so dropping and
-- recreating it loses nothing.
DROP TABLE IF EXISTS weekly_accountability_assignments;

CREATE TABLE weekly_accountability_assignments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id       BIGINT NOT NULL REFERENCES weekly_accountability_templates(id) ON DELETE CASCADE,
    week_id           BIGINT NOT NULL REFERENCES weekly_accountability_weeks(id) ON DELETE CASCADE,
    week_number       SMALLINT NOT NULL CONSTRAINT chk_weekly_acct_assignments_week_number CHECK (week_number BETWEEN 1 AND 4),
    cycle_month       DATE NOT NULL,
    assigned_at       TIMESTAMP(6) NOT NULL,
    -- Which of the cron's three trigger paths produced/last-touched this row - purely
    -- observability, same convention as the nightly cron's log lines.
    trigger_source    VARCHAR(30) NOT NULL
                          CONSTRAINT chk_weekly_acct_assignments_trigger_source
                              CHECK (trigger_source IN ('cron', 'startup-catch-up', 'periodic-safety-net')),
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    created_by        BIGINT,
    updated_by        BIGINT,
    -- One current assignment per template - a Saturday trigger updates this row in place
    -- rather than appending a new one each week.
    CONSTRAINT uk_weekly_acct_assignments_template UNIQUE (template_id)
);

CREATE INDEX idx_weekly_acct_assignments_week ON weekly_accountability_assignments(week_id);
