ALTER TABLE referral_resources
    DROP CONSTRAINT IF EXISTS chk_owner_type,
    ADD CONSTRAINT chk_owner_type CHECK (owner_type IN ('REFERRAL','COMPANY','SENIOR_COUNSELLOR','JUNIOR_COUNSELLOR','VIDEO_EDITOR','COUNSELLOR','MANAGER','BRANCH_PARTNER','ADMINISTRATIVE_ASSISTANT'));
