package com.lab.atlasmentor.enums;

/**
 * Enum representing the source of a task.
 * Used to track how tasks were created for auditing and analytics.
 */
public enum TaskSource {
    /**
     * Task created manually by a user
     */
    MANUAL,
    
    /**
     * Task generated automatically from a task bundle
     * @deprecated Not one of the values allowed by the {@code tasks_source_type_check} DB
     * constraint (MANUAL / TEMPLATE_GENERATED / SYSTEM_AUTOMATION) - inserting a Task with
     * this value fails at the DB layer. Kept only because {@link com.lab.atlasmentor.service.TaskGenerationService}
     * still sets it; do not use for new code. See {@link #TEMPLATE_GENERATED}.
     */
    @Deprecated
    TASK_BUNDLE,

    /**
     * Task generated from a Role Template's day-by-day content by
     * {@link com.lab.atlasmentor.service.TemplateInstantiationService} (cron, startup
     * catch-up, periodic safety-net, or Publish). One of the values the
     * {@code tasks_source_type_check} DB constraint actually allows.
     */
    TEMPLATE_GENERATED,

    /**
     * Task generated by system automation
     */
    SYSTEM_AUTOMATION,
    
    /**
     * Task generated from workflow engine
     */
    WORKFLOW
}
