package com.lab.atlasmentor.enums;

public enum TaskAction {
    CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ASSIGNED,
    COMMENT_ADDED,
    DUE_DATE_UPDATED,
    DUE_TIME_UPDATED,
    AUTO_GENERATED,
    BUNDLE_EXECUTED,
    BUNDLE_DEACTIVATED,
    TASK_ESCALATED,
    REMINDER_SENT,
    MARKED_OVERDUE,
    SUBTASK_ADDED,
    ATTACHMENT_ADDED,
    TAG_ADDED,
    WATCHER_ADDED,
    TIME_TRACKED,
    LIST_CHANGED,
    START_DATE_SET,
    DEPENDENCY_ADDED
}
