package com.lab.atlasmentor.enums;

/**
 * Enum representing the source of a task.
 * Used to track how tasks were created for auditing and analytics.
 */
public enum TaskSource {
    /**
     * Task created manually by a user
     */
    MANUAL,
    
    /**
     * Task generated automatically from a task bundle
     */
    TASK_BUNDLE,
    
    /**
     * Task generated by system automation
     */
    SYSTEM_AUTOMATION,
    
    /**
     * Task generated from workflow engine
     */
    WORKFLOW
}
