package com.lab.atlasmentor.enums;

public enum TaskAction {
    CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ASSIGNED,
    COMMENT_ADDED,
    DUE_DATE_UPDATED,
    AUTO_GENERATED,
    BUNDLE_EXECUTED,
    BUNDLE_DEACTIVATED,
    TASK_ESCALATED,
    REMINDER_SENT,
    MARKED_OVERDUE
}
